# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 16:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('column', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lmcolumn',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
