# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 02:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map_basic', '0016_auto_20170620_1529'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('column', '0002_lmcolumn_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='lmcolumn',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='lm_column_lm_tag', to='map_basic.LMTag'),
        ),
        migrations.AddField(
            model_name='lmcolumn',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
