# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 15:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map_basic', '0016_auto_20170620_1529'),
        ('column', '0003_auto_20170710_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='lmcolumn',
            name='cover_photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lm_column_lm_photo', to='map_basic.LMPhoto'),
        ),
    ]
