# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 04:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('column', '0004_lmcolumn_cover_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='lmcolumn',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
