# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 04:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('column', '0005_lmcolumn_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='lmcolumn',
            name='display',
            field=models.BooleanField(default=True),
        ),
    ]
