# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-15 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('column', '0006_lmcolumn_display'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lmcolumn',
            name='tags',
            field=models.ManyToManyField(blank=True, to='map_basic.LMTag'),
        ),
    ]
