# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-15 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('column', '0007_auto_20170715_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lmcolumn',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='lm_column_lm_tag', to='map_basic.LMTag'),
        ),
    ]
