# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-15 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_basic', '0017_lmtag_hide'),
        ('column', '0008_auto_20170715_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='lmcolumn',
            name='hide_tags',
            field=models.ManyToManyField(blank=True, related_name='lm_column_hide_lm_tag', to='map_basic.LMTag'),
        ),
    ]
