# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_map', '0002_auto_20170605_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='lmmapplace',
            name='display',
            field=models.BooleanField(default=True),
        ),
    ]
