# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-10 05:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map_map', '0003_lmmapplace_display'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lmmapplace',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='map_basic.LMPlace'),
        ),
    ]
