# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-10 05:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_basic', '0011_lmtag'),
        ('map_map', '0004_auto_20170610_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='lmmap',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='lm_map_map_lm_tag', to='map_basic.LMTag'),
        ),
        migrations.AddField(
            model_name='lmmapplace',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='lm_map_place_lm_tag', to='map_basic.LMTag'),
        ),
    ]
