# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 07:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map_map', '0006_lmmap_map_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lmmap',
            name='map_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='lm_map_image_lm_photo', to='map_basic.LMPhoto'),
        ),
    ]
