# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 06:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map_map', '0009_lmmapplace_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lmmap',
            name='attractions',
        ),
        migrations.RemoveField(
            model_name='lmmap',
            name='cities',
        ),
    ]
