# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 07:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map_map', '0010_auto_20170626_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lmmap',
            name='places',
        ),
    ]
