# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 03:49
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=225)),
                ('type', models.IntegerField(choices=[(0, 'MAP'), (1, 'STATICMAP'), (2, 'MAPDETAIL')], default=0)),
            ],
        ),
    ]
