# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 04:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicekey',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='servicekey',
            name='disable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicekey',
            name='last_month_key_get',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
