# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-05 07:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map_basic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lmplace',
            name='attraction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='map_basic.LMAttraction'),
        ),
        migrations.AlterField(
            model_name='lmplace',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='map_basic.LMCity'),
        ),
        migrations.AlterField(
            model_name='lmplace',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='map_basic.LMCountry'),
        ),
        migrations.AlterField(
            model_name='lmplace',
            name='photos',
            field=models.ManyToManyField(blank=True, related_name='lm_photo_ids', to='map_basic.LMPhoto'),
        ),
        migrations.AlterField(
            model_name='lmplace',
            name='place_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='lm_place_lm_place_type', to='map_basic.LMPlaceType'),
        ),
        migrations.AlterField(
            model_name='lmplace',
            name='rating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lm_place_lm_rating', to='map_basic.LMRating'),
        ),
    ]
