# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 09:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('map_basic', '0003_auto_20170607_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='lmattraction',
            name='createDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lmcity',
            name='createDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lmcountry',
            name='createDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
