# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-08 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_basic', '0004_auto_20170607_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lmplace',
            name='photos',
            field=models.ManyToManyField(blank=True, null=True, related_name='lm_photo_ids', to='map_basic.LMPhoto'),
        ),
    ]
