# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-08 07:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map_basic', '0006_auto_20170608_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lmplace',
            name='photos',
        ),
    ]
