# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_basic', '0007_remove_lmplace_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='lmplace',
            name='photos',
            field=models.ManyToManyField(blank=True, related_name='lm_photo_ids', to='map_basic.LMPhoto'),
        ),
    ]
