# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 15:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map_basic', '0008_lmplace_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lmplace',
            name='rating',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='map_basic.LMRating'),
        ),
    ]
