# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-10 05:41
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('map_basic', '0010_lmplace_display'),
    ]

    operations = [
        migrations.CreateModel(
            name='LMTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('createDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
