# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-11 14:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('map_basic', '0011_lmtag'),
    ]

    operations = [
        migrations.AddField(
            model_name='lmtag',
            name='createUser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
