# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 06:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map_basic', '0012_lmtag_createuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='lmplace',
            name='map_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lm_place_image_lm_photo', to='map_basic.LMPhoto'),
        ),
    ]
