# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_basic', '0013_lmplace_map_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='lmplace',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='lm_map_place_lm_tag', to='map_basic.LMTag'),
        ),
    ]
