# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 16:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('map_basic', '0014_lmplace_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='lmplace',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
