# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 07:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('map_basic', '0015_lmplace_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lmrating',
            name='total',
        ),
        migrations.RemoveField(
            model_name='lmrating',
            name='bad',
        ),
        migrations.AddField(
            model_name='lmrating',
            name='bad',
            field=models.ManyToManyField(blank=True, related_name='rating_bad_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='lmrating',
            name='good',
        ),
        migrations.AddField(
            model_name='lmrating',
            name='good',
            field=models.ManyToManyField(blank=True, related_name='rating_good_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
