# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-15 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_basic', '0016_auto_20170620_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='lmtag',
            name='hide',
            field=models.BooleanField(default=False),
        ),
    ]
